### ISSUE TITLE
Any Help, or maybe a possible fix?

### ISSUE THREAD

**Issue by 0x34d** [Cisco-Talos/covnavi#2]
/Error in import_coverage_info.py
ValueError: invalid literal for int() with base 10: '------------------'

/line_coverage.txt
#usr#include#c++#9#bits#basic_string.tcc.gcov		------------------
#usr#include#c++#9#bits#basic_string.tcc.gcov		_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructIPcEEvT_S7_St20forward_iterator_tag

**Comment by 0xMrBlack** [comment]
FIX:
	if coverage == "------------------":
		print("Not")	
	else:
		if not coverage == "#####" and not coverage == "-":
		    num_executions = int(coverage)
		conn.execute("INSERT INTO line_coverage VALUES (?,?,?)",(filename,line,num_executions))
		conn.commit()

**Comment by 0x34d** [comment]
FIX : 
		if not type(coverage) == int:
			print("not an int")
		else:
	    		num_executions = int(coverage)
